# Generated by Django 4.2.7 on 2023-11-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0001_initial'),
        ('user_profile', '0002_activationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(to='interest.interest'),
        ),
    ]
