# Generated by Django 4.2.7 on 2023-12-05 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interest', '0002_remove_interest_created_by'),
        ('user_profile', '0006_remove_userprofile_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('max_num_participants', models.IntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('interests', models.ManyToManyField(to='interest.interest')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InterestGroupParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_warns', models.IntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
                ('interest_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interest_group.interestgroup')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
            options={
                'unique_together': {('interest_group', 'participant')},
            },
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='participants',
            field=models.ManyToManyField(related_name='participant_interest_group', through='interest_group.InterestGroupParticipant', to='user_profile.userprofile'),
        ),
    ]
